data_collection:
  duration: 3600

safety:
  margin_close: 2.0
  margin_open: 3.0
  driver_reaction: 2.5

sensor_calculation:
  detection_margin: 1.3
  sensor_0_multiplier: 3.0
  sensor_1_multiplier: 1.8
  sensor_2_multiplier: 0.9
  min_sensor_distance: 300
  max_sensor_0: 1500
  max_sensor_1: 1000
