network:
  road_separation: 200
  crossing_distance: 300
  road_length: 2000

traffic:
  cars_per_hour: 300
  train_interval: 180

crossings:
  west:
    sensors: [1200, 800, 400]
    close_before_arrival: 8.0
    open_after_departure: 5.0
    warning_time: 25.0

  east:
    sensors: [1500, 900, 450]
    close_before_arrival: 10.0
    open_after_departure: 3.0
    warning_time: 30.0

fuel:
  driving: 0.08
  idling: 0.01
  engine_off: 0.0
  co2_per_liter: 2.31
  min_wait_to_shutoff: 5.0
  engine_off_factor: 0.7

rerouting:
  min_time_saved: 8.0
  decision_point: 180

simulation:
  duration: 1200
  step_size: 0.1
