network:
  road_separation: 200
  crossing_distance: 300
  road_length: 2000

traffic:
  cars_per_hour: 1200
  train_interval: 240

crossings:
  west:
    sensors: [1200, 800, 400]
    close_before_arrival: 120.0
    open_after_departure: 180.0
    warning_time: 150.0

  east:
    sensors: [1500, 900, 450]
    close_before_arrival: 60.0
    open_after_departure: 90.0
    warning_time: 90.0

routing:
  travel_time_west_to_east: 180.0
  reroute_threshold: 60.0
  adoption_rate: 0.70

fuel:
  driving: 0.08
  idling: 0.01
  engine_off: 0.0
  co2_per_liter: 2.31
  min_wait_to_shutoff: 5.0

simulation:
  duration: 3600
  step_size: 0.1
