closure_before_eta: 10.0
opening_after_etd: 3.0
notification_time: 37.5
sensor_positions:
- 1500.0
- 900.0
- 450.0
max_train_speed: 50.0
engine_off_threshold: 5.0
statistics:
  clearance_samples: 0
  train_samples: 20
  travel_samples: 0
  clearance_mean: 0.0
  clearance_95th: 0.0
  clearance_max: 0.0
  passage_mean: 0.0
  passage_max: 0.0
  travel_mean: 0.0
  travel_95th: 0.0
  observed_max_speed: 0.0
  ml_max_speed: 50.0
  used_max_speed: 50.0
